{
// Example of Root macro to copy a subset of a Tree to a new Tree
// The input file has been generated by the program in $ROOTSYS/test/Event
// with   Event 1000 1 99 1

   gROOT->Reset();

   //Get old file, old tree and set top branch address
   TFile *oldfile = new TFile("periodAll.root");
   TTree *oldtree = (TTree*)oldfile->Get("fit_results");
   Int_t nentries = (Int_t)oldtree->GetEntries();

   //Create a new file + a clone of old tree in new file

   for (Int_t i=0;i<nentries; i++) {
      TFile *newfile = new TFile(Form("%d.root",2014+i),"recreate");
      TTree *newtree = oldtree->CloneTree(0);
      oldtree->GetEntry(i);
      newtree->Fill();
      newtree->AutoSave();
      delete newfile;
   }
   delete oldfile;
}


